### ISSUE TITLE
openwrt 22.03 stable release Device [openwrt] async_update_data error: rpc error: 2

### ISSUE THREAD

**Issue by amirudon** [kvj/hass_openwrt#11]
could not connect to openwrt 22.03

home assistant giving error:
Device [openwrt] async_update_data error: rpc error: 2

logs from home assistant:
Traceback (most recent call last):
  File "/config/custom_components/openwrt/coordinator.py", line 250, in async_update_data
    result["wan"] = await self.update_wan_info()
  File "/config/custom_components/openwrt/coordinator.py", line 215, in update_wan_info
    response = await self._ubus.api_call(
  File "/config/custom_components/openwrt/ubus.py", line 41, in api_call
    return await self._api_call(rpc_method, subsystem, method, params)
  File "/config/custom_components/openwrt/ubus.py", line 121, in _api_call
    raise ConnectionError(f"rpc error: {result[0]}")
ConnectionError: rpc error: 2

**Comment by BosakS** [comment]
Same error:
2023-02-12 00:50:54.069 ERROR (MainThread) [custom_components.openwrt.coordinator] Device [OpenWrt] async_update_data error: rpc error: 2
Traceback (most recent call last):
  File "/config/custom_components/openwrt/coordinator.py", line 252, in async_update_data
    result["wan"] = await self.update_wan_info()
  File "/config/custom_components/openwrt/coordinator.py", line 217, in update_wan_info
    response = await self._ubus.api_call(
  File "/config/custom_components/openwrt/ubus.py", line 41, in api_call
    return await self._api_call(rpc_method, subsystem, method, params)
  File "/config/custom_components/openwrt/ubus.py", line 121, in _api_call
    raise ConnectionError(f"rpc error: {result[0]}")
ConnectionError: rpc error: 2

**Comment by JorgenEvens** [comment]
In my case this was caused by entering the **interface** names rather than the actual **device** names for WAN and WLAN devices.

You can find the device names by hovering over the icons shown for an interface.
![image](https://user-images.githubusercontent.com/223318/229346895-531bc2d9-2598-467e-b959-b67d116eca9f.png)
