### ISSUE TITLE
Unable to communicate with router SSL error

### ISSUE THREAD

**Issue by mwitlox** [kvj/hass_openwrt#4]
Hi!

First seems like a great intergration! Would like to test this. But not able to complete the config. Did al the steps but getting a SSL error.

Logger: custom_components.openwrt.ubus
Source: custom_components/openwrt/ubus.py:92
Integration: OpenWrt ([documentation](https://github.com/kvj/hass_openwrt), [issues](https://github.com/kvj/hass_openwrt/issues))
First occurred: 16:10:27 (2 occurrences)
Last logged: 16:10:47

api_call exception: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

Logger: custom_components.openwrt.coordinator
Source: custom_components/openwrt/ubus.py:93
Integration: OpenWrt ([documentation](https://github.com/kvj/hass_openwrt), [issues](https://github.com/kvj/hass_openwrt/issues))
First occurred: 16:10:27 (2 occurrences)
Last logged: 16:10:47

Device [Test] async_update_data error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openwrt/ubus.py", line 90, in _api_call
    response = await self.executor_job(post)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openwrt/ubus.py", line 84, in post
    return requests.post(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openwrt/coordinator.py", line 243, in async_update_data
    self._apis = await self.load_ubus()
  File "/config/custom_components/openwrt/coordinator.py", line 232, in load_ubus
    return await self._ubus.api_call("*", None, None, "list")
  File "/config/custom_components/openwrt/ubus.py", line 44, in api_call
    await self._login()
  File "/config/custom_components/openwrt/ubus.py", line 48, in _login
    result = await self._api_call(
  File "/config/custom_components/openwrt/ubus.py", line 93, in _api_call
    raise ConnectionError from err
ConnectionError

Logger: homeassistant.config_entries
Source: config_entries.py:370
First occurred: 16:10:47 (1 occurrences)
Last logged: 16:10:47

Config entry 'Test - 192.168.1.1' for openwrt integration not ready yet: OpenWrt communication error: ; Retrying in background

![image](https://user-images.githubusercontent.com/96582378/172868604-800fe2f7-1226-4bc8-84f4-4fb543b5c73e.png)

I don't use any certificate, no HTTPS. What am i doing wrong? Can u help :)?

**Comment by mwitlox** [comment]
Hi,
I tried both, checkbox on/off same error
Got 4 TP Links Archer C7's v2 running on 21.02.3

Also tried root user for login. Same error

**Comment by kvj** [comment]
Please refer to https://www.home-assistant.io/integrations/logger/ on how to enable logging

**Comment by mwitlox** [comment]
![image](https://user-images.githubusercontent.com/96582378/173058908-fe4735ed-c95f-474d-ac1e-b48971515c78.png)

Added to configuration.yaml
Restart HA
Checked

![image](https://user-images.githubusercontent.com/96582378/173058999-cc180c5b-cd3a-4a89-9521-78e5847fa124.png)

Same thing, nothing more then what i send before. Did i miss something?

**Comment by mwitlox** [comment]
Unable to get the right information out of my system. Closing this case.

**Comment by shampeon** [comment]
I'm getting the same error.

~~~
api_call exception: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
~~~

I use a self-signed certificate on my OpenWRT router, which will automatically upgrade any non-HTTP requests to HTTPS. I get the error whether or not I check *Use HTTPS*.

~~~
 Device [openwrt] async_update_data error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/openwrt/ubus.py", line 90, in _api_call
    response = await self.executor_job(post)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openwrt/ubus.py", line 84, in post
    return requests.post(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.0.1', port=443): Max retries exceeded with url: /ubus (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/openwrt/coordinator.py", line 243, in async_update_data
    self._apis = await self.load_ubus()
  File "/config/custom_components/openwrt/coordinator.py", line 232, in load_ubus
    return await self._ubus.api_call("*", None, None, "list")
  File "/config/custom_components/openwrt/ubus.py", line 44, in api_call
    await self._login()
  File "/config/custom_components/openwrt/ubus.py", line 48, in _login
    result = await self._api_call(
  File "/config/custom_components/openwrt/ubus.py", line 93, in _api_call
    raise ConnectionError from err
ConnectionError
~~~

And `new_coordinator` debug lines from `home_assistant.log`:

~~~
2022-07-28 09:34:23 DEBUG (MainThread) [custom_components.openwrt.coordinator] new_coordinator: {'id': 'openwrt', 'address': '192.168.0.1', 'username': 'hass', 'https': False, 'port': 0, 'path': '/ubus', 'wps': False, 'password': 'xxxxxxx'}
2022-07-28 09:34:33 DEBUG (MainThread) [custom_components.openwrt.coordinator] new_coordinator: {'id': 'openwrt', 'address': '192.168.0.1', 'username': 'hass', 'https': False, 'port': 0, 'path': '/ubus', 'wps': False, 'password': 'xxxxxxx'}
2022-07-28 09:34:44 DEBUG (MainThread) [custom_components.openwrt.coordinator] new_coordinator: {'id': 'openwrt', 'address': '192.168.0.1', 'username': 'hass', 'https': False, 'port': 0, 'path': '/ubus', 'wps': False, 'password': 'xxxxxxx'}
2022-07-28 09:34:44 DEBUG (MainThread) [custom_components.openwrt.ubus] New call [http://192.168.0.1/ubus] {"jsonrpc": "2.0", "id": 1, "method": "call", "params": ["00000000000000000000000000000000", "session", "login", {"username": "hass", "password": "xxxxxxx"}]}
2022-07-28 09:35:45 DEBUG (MainThread) [custom_components.openwrt.coordinator] new_coordinator: {'id': 'openwrt', 'address': '192.168.0.1', 'username': 'hass', 'https': False, 'port': 0, 'path': '/ubus', 'wps': False, 'password': 'xxxxxxx'}
2022-07-28 09:35:45 DEBUG (MainThread) [custom_components.openwrt.ubus] New call [http://192.168.0.1/ubus] {"jsonrpc": "2.0", "id": 1, "method": "call", "params": ["00000000000000000000000000000000", "session", "login", {"username": "hass", "password": "xxxxxxx"}]}
~~~

**Comment by shampeon** [comment]
FWIW, I just followed the instructions [here](https://openwrt.org/docs/guide-user/luci/luci.essentials#providing_encryption) and [here](https://openwrt.org/docs/guide-user/luci/luci.secure) to enable self-signed certs.
